version: 2
registries:
  github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/frankhambach/index.json
    token: ${{ secrets.GITHUB_TOKEN }}
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly